package com.bendemenstudios.steampunksync.client;
import com.bendemenstudios.steampunksync.model.VersionManifest;
import java.io.*; import java.net.URI; import java.net.http.*; import java.nio.file.*; import java.security.MessageDigest; import java.time.Duration; import java.util.Comparator; import java.util.HexFormat; import java.util.zip.*;
public final class PackSynchronizer {
 private static final HttpClient HTTP=HttpClient.newBuilder().followRedirects(HttpClient.Redirect.NORMAL).connectTimeout(Duration.ofSeconds(15)).build(); private PackSynchronizer(){}
 public static SyncResult downloadAndInstall(VersionManifest m, Path gameDir, ProgressListener l){Path zip=gameDir.resolve(".steampunksync-download.tmp"), stage=gameDir.resolve(".steampunksync-staging"), managed=gameDir.resolve("steampunksync-managed"); try{Files.createDirectories(gameDir);Files.deleteIfExists(zip);deleteTree(stage);Files.createDirectories(stage);HttpResponse<InputStream> r=HTTP.send(HttpRequest.newBuilder(URI.create(m.download())).timeout(Duration.ofMinutes(20)).GET().build(),HttpResponse.BodyHandlers.ofInputStream());if(r.statusCode()/100!=2)return SyncResult.fail("Download failed: HTTP "+r.statusCode());MessageDigest d=MessageDigest.getInstance("SHA-256");long total=m.size()>0?m.size():r.headers().firstValueAsLong("Content-Length").orElse(-1),done=0;try(InputStream in=r.body();OutputStream out=Files.newOutputStream(zip)){byte[] b=new byte[1024*1024];for(int n;(n=in.read(b))!=-1;){d.update(b,0,n);out.write(b,0,n);done+=n;l.update(done,total,"Downloading modpack");}}if(m.sha256()==null||m.sha256().isBlank()||!HexFormat.of().formatHex(d.digest()).equalsIgnoreCase(m.sha256().trim()))return SyncResult.fail("SHA-256 verification failed");extractSafe(zip,stage);deleteTree(managed);try{Files.move(stage,managed,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException e){Files.move(stage,managed,StandardCopyOption.REPLACE_EXISTING);}Files.deleteIfExists(zip);return SyncResult.ok("Installed "+m.version());}catch(Exception e){try{Files.deleteIfExists(zip);deleteTree(stage);}catch(Exception ignored){}return SyncResult.fail(e.getClass().getSimpleName()+": "+e.getMessage());}}
 private static void extractSafe(Path zip,Path root)throws IOException{root=root.toAbsolutePath().normalize();try(ZipInputStream z=new ZipInputStream(Files.newInputStream(zip))){for(ZipEntry e;(e=z.getNextEntry())!=null;){String n=e.getName().replace('\\','/');if(n.isBlank()||n.startsWith("/")||n.matches("^[A-Za-z]:.*")||n.contains("../")||n.contains("/.."))throw new IOException("Unsafe ZIP entry: "+n);Path t=root.resolve(n).normalize();if(!t.startsWith(root))throw new IOException("ZIP path traversal blocked");if(e.isDirectory())Files.createDirectories(t);else{Files.createDirectories(t.getParent());try(OutputStream o=Files.newOutputStream(t)){z.transferTo(o);}}z.closeEntry();}}}
 private static void deleteTree(Path p)throws IOException{if(!Files.exists(p))return;try(var w=Files.walk(p)){w.sorted(Comparator.reverseOrder()).forEach(x->{try{Files.deleteIfExists(x);}catch(IOException e){throw new UncheckedIOException(e);}});}}
 @FunctionalInterface public interface ProgressListener{void update(long done,long total,String stage);}
}
