package com.bendemenstudios.steampunksync.client;
import com.bendemenstudios.steampunksync.model.VersionManifest;
import net.minecraft.client.gui.GuiGraphics;import net.minecraft.client.gui.components.Button;import net.minecraft.client.gui.screens.Screen;import net.minecraft.network.chat.Component;import java.util.Locale;
public final class SteampunkSyncScreen extends Screen{
 private final VersionManifest manifest;private volatile long done,total;private volatile double bytesPerSecond;private volatile String status="Ready to update";private volatile boolean running,completed;private Button actionButton;
 public SteampunkSyncScreen(VersionManifest manifest){super(Component.literal("SteampunkSync"));this.manifest=manifest;}
 @Override protected void init(){actionButton=Button.builder(Component.literal("UPDATE NOW"),b->start()).bounds(width/2-80,height/2+55,160,20).build();addRenderableWidget(actionButton);}
 private void start(){if(running)return;running=true;status="Starting...";if(actionButton!=null)actionButton.active=false;Thread.startVirtualThread(()->{SyncResult r=PackSynchronizer.downloadAndInstall(manifest,minecraft.gameDirectory.toPath(),(d,t,s,speed)->{done=d;total=t;bytesPerSecond=speed;status=s;});minecraft.execute(()->{running=false;status=r.message();if(r.success()){ClientUpdateState.setInstalledVersion(minecraft.gameDirectory.toPath(),manifest.version());completed=true;clearWidgets();actionButton=Button.builder(Component.literal("RESTART MINECRAFT"),b->restart()).bounds(width/2-90,height/2+55,180,20).build();addRenderableWidget(actionButton);}else{clearWidgets();actionButton=Button.builder(Component.literal("TRY AGAIN"),b->start()).bounds(width/2-80,height/2+55,160,20).build();addRenderableWidget(actionButton);}});});}
 private void restart(){if(!completed||running)return;status="Restarting Minecraft...";minecraft.stop();}
 @Override public void render(GuiGraphics g,int mx,int my,float pt){renderBackground(g,mx,my,pt);int cx=width/2;g.drawCenteredString(font,"STEAMPUNK SYNC",cx,height/2-95,0xFFD18A45);g.drawCenteredString(font,manifest.modpack()+" • "+manifest.version(),cx,height/2-72,0xFFFFFFFF);g.drawCenteredString(font,"A new modpack version is available",cx,height/2-50,0xFFC0C0C0);int y=height/2+20,w=320,x=cx-w/2;g.fill(x,y,x+w,y+8,0xFF29231D);if(total>0){int fill=(int)Math.min(w,Math.max(0,done*(double)w/total));g.fill(x,y,x+fill,y+8,0xFFD18A45);}String progress=total>0?formatBytes(done)+" / "+formatBytes(total)+" • "+formatSpeed(bytesPerSecond):status;g.drawCenteredString(font,progress,cx,y+18,0xFFFFFFFF);g.drawCenteredString(font,status,cx,y+32,0xFFC0C0C0);if(manifest.releaseNotes()!=null&&!manifest.releaseNotes().isEmpty()){g.drawCenteredString(font,"WHAT'S NEW",cx,y+52,0xFFD18A45);int yy=y+67;for(String note:manifest.releaseNotes()){g.drawCenteredString(font,"• "+note,cx,yy,0xFFE0E0E0);yy+=12;if(yy>height-20)break;}}super.render(g,mx,my,pt);}
 private static String formatBytes(long v){if(v<1024)return v+" B";if(v<1024*1024)return String.format(Locale.ROOT,"%.1f KiB",v/1024d);if(v<1024L*1024*1024)return String.format(Locale.ROOT,"%.1f MiB",v/(1024d*1024));return String.format(Locale.ROOT,"%.2f GiB",v/(1024d*1024*1024));}
 private static String formatSpeed(double bps){return bps>0?formatBytes((long)bps)+"/s":"calculating speed...";}@Override public boolean shouldCloseOnEsc(){return !running;}}
